name: "Build and check RTL2GDS"
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test-designs:
    name: test RTL2GDS - ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: gcd
            config_file: gcd.yaml
            dir: gcd
          - name: picorv32a
            config_file: pico.yaml
            dir: picorv32a
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/determinate-nix-action@v3
      - name: Run ${{ matrix.name }} flows
        run: |
          export PYTHONPATH=${GITHUB_WORKSPACE}/src:${PYTHONPATH}
          cd design_zoo/${{ matrix.dir }}
          nix shell nixpkgs#python312Packages.pyyaml nixpkgs#python312Packages.orjson nixpkgs#python312Packages.klayout nixpkgs#python312 nixpkgs#python312Packages.pip nixpkgs#ieda nixpkgs#yosys -c " \\
              echo '--- Environment in Nix Shell ---' && ls -alh . && \\
              python3 -m rtl2gds -c ${{ matrix.config_file }} \\
            "
